name: mtn_chatbot
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dialogflow_grpc: ^0.2.9
  intl: ^0.17.0
  provider: ^6.0.4
  sound_stream:
    git:
      url: https://github.com/satymshrma/flutter-sound-stream.git
      ref: patch-1
  rxdart: ^0.27.6
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  firebase_auth: ^4.0.2
  firebase_core: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.3+1

flutter_native_splash:
  color: "#FFCB01"
  image: "assets/rsz_mtn_logo.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/mtn_logo.png"
  remove_alpha_ios: true
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/rsz_mtn_logo.png
    - assets/credentials.json
# FFCB01
